#!/bin/bash
spark-submit --packages com.databricks:spark-csv_2.10:1.5.0 \
--class example.SparkWordCount --master local \
--deploy-mode client --executor-memory 1g  \
--name wordcount --conf "spark.app.id=wordcount" \
--jars /home/centos/mysql/mysql-connector-java-5.1.44.jar ./sparkwordcount-0.0.1-SNAPSHOT.jar 2